Repository autoever-ob/OB-iOS, pull requests merged in 2025-09, with the labels that each got.

#5 #4 feat(home): 홈 화면 구현
  .DS_Store
  campick/Assets.xcassets/bannerImage.imageset/Contents.json
  campick/Assets.xcassets/bannerImage.imageset/bannerImage.png
  campick/Assets.xcassets/bottomBannerImage.imageset/Contents.json
  campick/Assets.xcassets/bottomBannerImage.imageset/bottomBannerImage.png
  campick/Assets.xcassets/category.imageset/Contents.json
  campick/Assets.xcassets/category.imageset/categoryImage.png
  campick/Assets.xcassets/testImage1.imageset/Contents.json
  campick/Assets.xcassets/testImage1.imageset/testImage1.png
  campick/Assets.xcassets/testImage2.imageset/Contents.json
  campick/Assets.xcassets/testImage2.imageset/testImage2.png
  campick/ContentView.swift
  campick/Extensions/Color+Hex.swift
  campick/Views/Components/BottomTabBar.swift
  campick/Views/HomeView.swift
Labels: feat

#9 #4 feat(home): 홈 화면 구현
  .DS_Store
  .gitignore
  campick/Views/Components/BottomTabBar.swift
  campick/Views/HomeView.swift
Labels: feature

#11 #10 fix: .gitignore 설정
  .gitignore
Labels: bug

#26 #14 feat(chatroom): 채팅 뷰 구현
  campick/Assets.xcassets/choi.imageset/Contents.json
  campick/Assets.xcassets/choi.imageset/choi.png
  campick/Assets.xcassets/mrchu.imageset/Contents.json
  campick/Assets.xcassets/mrchu.imageset/mrchu.jpeg
  campick/Assets.xcassets/park.imageset/Contents.json
  campick/Assets.xcassets/park.imageset/park.jpeg
  campick/Assets.xcassets/tiffany.imageset/Contents.json
  campick/Assets.xcassets/tiffany.imageset/tiffany.jpeg
  campick/Models/Message.swift
  campick/Models/Vehicle.swift
  campick/Views/ChatRoomListView.swift
  campick/Views/ChatView.swift
  campick/Views/Components/TabBar/BottomTabBar.swift
  campick/Views/HomeView.swift
Labels: feature

#28 #14 feat(chatroom): temp
  campick/Info.plist
Labels: feature

#30 #29 feat(alamofire): API 레이어 구조화 및 interceptor 적용
  campick.xcodeproj/project.pbxproj
  campick/Info.plist
  campick/Services/Network/APIService.swift
  campick/Services/Network/AuthInterceptor.swift
  campick/Services/Network/Endpoints.swift
  campick/Services/Network/TokenManager.swift
Labels: feature

#35 Feat/#31 chatroom
  campick/Views/ChatRoomListView.swift
  campick/Views/ChatRoomView.swift
  campick/Views/HomeView.swift
Labels: feature

#43 #38 refactor(home): 컴포넌트 분리
  campick/Views/Components/Home/BottomBanner.swift
  campick/Views/Components/Home/FindVehicle.swift
  campick/Views/Components/Home/Header.swift
  campick/Views/Components/Home/MenuItem.swift
  campick/Views/Components/Home/ProfileMenu.swift
  campick/Views/Components/Home/RecommendVehicle.swift
  campick/Views/Components/Home/TopBanner.swift
  campick/Views/Components/Home/VehicleCategory.swift
  campick/Views/HomeView.swift
Labels: refactor

#73 #47 feat: 매물 찾기 API 연동 및 모델들 생성
  campick/Models/Product/ProductCreateRequest.swift
  campick/Models/Product/ProductDetailDTO.swift
  campick/Models/Product/ProductItemDTO.swift
  campick/Models/Product/ProductListDTO.swift
  campick/Models/Product/ProductUpdateRequest.swift
  campick/Services/ProductAPI.swift
  campick/ViewModels/FindVehicleViewModel.swift
Labels: feature

#77 #76 fix(favorites,home): 빌드 오류 제거 & 네비게이션 스택 추가
  campick/Views/FavoritesView.swift
  campick/Views/HomeView.swift
Labels: fix

#81 #80 fix(bottomtabbar): 바텀 탭 바 버그 수정
  campick/RootView.swift
  campick/Views/ChatRoomListView.swift
  campick/Views/Components/Home/ProfileMenu.swift
  campick/Views/HomeView.swift
Labels: bug, fix

#87 #71 feat: 비밀번호 찾기 페이지 생성
  campick/Services/AuthAPI.swift
  campick/ViewModels/FindPasswordViewModel.swift
  campick/Views/FindPasswordView.swift
Labels: feature

#90 #86 feat: 로그인 시 유저 메타 데이터 프로필에 연결
  campick/Models/Auth/AuthResponse.swift
  campick/Models/Auth/DecodingExtensions.swift
  campick/Models/Auth/LoginDataDTO.swift
  campick/Models/Auth/UserDTO.swift
  campick/Models/UserState.swift
  campick/RootView.swift
  campick/Services/AuthAPI.swift
  campick/Utils/AppLog.swift
  campick/ViewModels/LoginViewModel.swift
  campick/ViewModels/ProfileDataViewModel.swift
  campick/ViewModels/SignupFlowViewModel.swift
  campick/Views/Auth/Signup/SignupFlowView.swift
  campick/Views/Components/Home/Header.swift
  campick/Views/Components/Home/ProfileMenu.swift
Labels: feature

#95 #91 refactor: 매물 찾기 및 상세 조회 api 연동 완료
  campick/Models/Common/Page.swift
  campick/Models/Product/ProductDetailDTO.swift
  campick/Models/Product/ProductItemDTO.swift
  campick/Models/Product/ProductListDTO.swift
  campick/Models/Profile/ProfileProductModels.swift
  campick/Models/UserProfile.swift
  campick/Services/Network/Endpoints.swift
  campick/Services/ProductAPI.swift
  campick/Services/ProfileService.swift
  campick/ViewModels/FindVehicleViewModel.swift
  campick/ViewModels/ProfileDataViewModel.swift
  campick/ViewModels/VehicleDetailViewModel.swift
  campick/Views/Components/Profile/ProductListSection.swift
  campick/Views/Components/VehicleDetail/VehicleDescriptionCard.swift
  campick/Views/Components/VehicleDetail/VehicleFeaturesCard.swift
  campick/Views/Components/VehicleDetail/VehicleImageGallery.swift
  campick/Views/Components/VehicleDetail/VehicleInfoCard.swift
  campick/Views/Components/VehicleDetail/VehicleSellerCard.swift
  campick/Views/FindVehicleView.swift
  campick/Views/ProfileView.swift
  campick/Views/VehicleDetailView.swift
Labels: refactor, feature

#99 #50 feat: 카메라 및 갤러리 이용 권한 기능 추가
  campick/Services/MediaPermissionManager.swift
  campick/Views/ChatRoomView.swift
  campick/Views/Components/ChatRoom/AttachmentMenu.swift
  campick/Views/Components/Media/ImagePickerView.swift
  campick/Views/Components/Media/MediaPickerSheet.swift
  campick/Views/Components/Profile/ProfileEditModal.swift
  campick/Views/Components/VehicleRegistration/VehicleImageUploadSection.swift
Labels: feature

#102 #83 feat(profile,home): API 연동
  campick/Models/RecommendedVehicle.swift
  campick/Services/Network/Endpoints.swift
  campick/Services/VehicleService.swift
  campick/ViewModels/HomeProfileViewModel.swift
  campick/ViewModels/HomeVehicleViewModel.swift
  campick/Views/Components/Home/ProfileMenu.swift
  campick/Views/Components/Home/RecommendVehicle.swift
Labels: feature

#108 #107 feat(auth): 로그아웃 API 연동 정정 및 로깅
  campick/Services/AuthService.swift
  campick/ViewModels/HomeProfileViewModel.swift
  campick/Views/ProfileView.swift
Labels: feature, fix

#110 #109 fix: 이미지 등록 API 재연동
  campick/Services/ImageUploadService.swift
  campick/Services/ProductAPI.swift
  campick/Views/VehicleRegistrationView.swift
Labels: feature, fix

#128 #89 refactor(profilemenu): 프로필 메뉴 애니메이션 버그 수정
  campick/RootView.swift
  campick/Views/Components/Home/ProfileMenu.swift
Labels: bug, refactor

#130 #124 feat: 홈화면이 아닌 다른 화면에서 매물 목록 조회 시, 바텀 탭바가 나타나도록 수정
  campick/Navigation/TabRouter.swift
  campick/RootView.swift
  campick/Views/Components/Home/FindVehicle.swift
  campick/Views/FindVehicleView.swift
  campick/Views/HomeView.swift
Labels: feature

#139 #113 refactor(filter): 연료·변속기 필터 제거, 핵심 필터만 유지
  campick/Views/Components/VehicleFinder/FilterView.swift
Labels: refactor

#143 #142 fix(camera): 카메라 사용 화면에 .ignoresSafeArea 적용
  campick/Views/Components/Media/MediaPickerSheet.swift
  campick/Views/Components/VehicleRegistration/VehicleImageUploadSection.swift
Labels: fix

#144 #129 refactor(eventDetail): 텍스트 폰트 조절
  campick/Views/EventDetailView.swift
Labels: refactor

#145 #140 fix: 프로필 이미지 등록 및 프로필 수정 에러 수정
  campick/Services/ProfileService.swift
  campick/Views/Components/Profile/ProfileEditModal.swift
Labels: fix

#147 #146 fix(detail): 헤더 이미지 Safe Area 확장 및 상단 잘림 보정
  campick/Views/Components/VehicleDetail/VehicleImageGallery.swift
  campick/Views/VehicleDetailView.swift
Labels: fix

#149 #148 fix: 카드 뷰 데이터 연동
  campick/Models/Product/MyProductListDTO.swift
  campick/Models/Product/ProductItemDTO.swift
  campick/ViewModels/HomeVehicleViewModel.swift
  campick/ViewModels/MyProductListViewModel.swift
  campick/Views/Components/Home/RecommendVehicle.swift
  campick/Views/Components/Profile/ProductListSection.swift
  campick/Views/Components/VehicleCardView.swift
Labels: fix

#191 #190 fix(chat): 채팅방 & 채팅 리스트 버그 수정
  campick.xcodeproj/project.pbxproj
  campick/Info.plist
  campick/Services/Network/WebSocket.swift
  campick/ViewModels/ChatViewModel.swift
  campick/Views/ChatRoomListView.swift
Labels: fix
